import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { BackgroundEffects } from "@/components/background-effect";
import { ProfileHeader } from "@/components/profile-header";
import Container from "@/components/container";
import AnimationWrapper from "@/components/animation-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          disableTransitionOnChange
          defaultTheme="dark"
        >
          <BackgroundEffects />
          <AnimationWrapper>
            <div className="grid grid-cols-1 md:grid-cols-[280px_1fr] gap-6">
              <ProfileHeader />
              <Container>{children}</Container>
            </div>
          </AnimationWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
